################ CRUD USER ################

### Create Admin User
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "ferdyfauzan",
    "password": "ferdyfauzan123",
    "role": 0
}

### Create General User
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "rakamahardika",
    "password": "rakamahardika123",
    "role": 1
}

### Read User
GET http://localhost:5000/users

### Delete User
DELETE http://localhost:5000/users/2

################ CRUD IDENTITY ################

### Create User Identity
POST http://localhost:5000/users/1/identities
Content-Type: application/json

{
    "name": "Mochamad Ferdy Fauzan",
    "image": "https://example.com/ferdy.jpg",
    "place_of_birth": "Garut",
    "date_of_birth": "2003-01-13",
    "address": "Komplek Serra Valley D6, Bandung",
    "phone_number": "085156600480",
    "email": "m.ferdyfauzan@example.com",
    "description": "A passionate web developer with a love for coding.",
    "userId": 1
}

### Create User Identity
POST http://localhost:5000/users/2/identities
Content-Type: application/json

{
    "name": "Raka Mahardika Maulana",
    "image": "https://example.com/raka.jpg",
    "place_of_birth": "Bandung",
    "date_of_birth": "2003-08-17",
    "address": "Cinunuk, Bandung",
    "phone_number": "085156444444",
    "email": "mahardika@example.com",
    "description": "A passionate web developer with a love for coding.",
    "userId": 2
}

### Read All Identities
GET http://localhost:5000/identities

### Read Identity by User Id
GET http://localhost:5000/users/1/identities

### Read Identity by User Id and Identity Id
GET http://localhost:5000/users/2/identities/2

### Update Identity by User Id and Identity Id
PATCH http://localhost:5000/users/1/identities/1
Content-Type: application/json

{
    "name": "Mochamad Ferdy Fauzan",
    "image": "https://example.com/ferdy.png",
    "place_of_birth": "Garut",
    "date_of_birth": "2003-01-13",
    "address": "Perum Cijati Asri S 10, Garut",
    "phone_number": "085156600480",
    "email": "m.ferdyfauzan@gmail.com",
    "description": "A passionate web developer with a love for coding."
}

### Delete Identity by User Id and Identity Id
DELETE http://localhost:5000/users/2/identities/3

################ CRUD EDUCATION ################

### GET all education records
GET http://localhost:5000/educations

### GET education records by identity id
GET http://localhost:5000/users/1/identities/1/educations

### GET education records by identity id and education id
GET http://localhost:5000/users/1/identities/1/educations/1

### Create a new education record for a user
POST http://localhost:5000/users/1/identities/1/educations
Content-Type: application/json

{
    "name_sch": "Example School",
    "image": null,
    "start_year": 2015,
    "end_year": 2020,
    "major": "Computer Science",
    "information": "Some information about the education",
    "identityId" : 1
    
}

### Update an education record by education_id and identity_id
PATCH http://localhost:5000/users/1/identities/1/educations/1
Content-Type: application/json

{
    "name_sch": "SMA Negeri 1 Garut",
    "image": null,
    "start_year": 2018,
    "end_year": 2021,
    "major": "Matematika dan IPA",
    "information": "Aktif di MPK\nLolos ke PTN jalur SNMPTN"
}

### Delete an education record by education_id and user_id
DELETE http://localhost:5000/users/1/identities/2/educations/5

################ CRUD ORGANIZATION ################

### GET all organization records
GET http://localhost:5000/organizations

### GET organization records by identity id
GET http://localhost:5000/users/1/identities/1/organizations

### GET organization records by identity id and organization id
GET http://localhost:5000/users/1/identities/1/organizations/2

### Create a new organization record for a user
POST http://localhost:5000/users/2/identities/2/organizations
Content-Type: application/json

{
    "name_org": "AIESEC",
    "image": null,
    "start_year": 2020,
    "end_year": 2023,
    "role": "Leader",
    "jobdesc": "Some information about the jobdesc",
    "identityId": 2
}

### Update an organization record by education_id and identity_id
PATCH http://localhost:5000/users/1/identities/1/organizations/1
Content-Type: application/json

{
    "name_org": "Himpunan Mahasiswa Komputer",
    "image": null,
    "start_year": 2021,
    "end_year": 2022,
    "role": "Human Resource Department Member",
    "jobdesc": "Some information about the jobdesc"
}

### Delete an organizations record by education_id and user_id
DELETE http://localhost:5000/users/1/identities/2/organizations/1

### GET education records by identity id
GET http://localhost:5000/users/1/identities/2/portfolios

### Delete an education record by education_id and user_id
GET http://localhost:5000/portfolios

