// =================== CRUD USER ====================
// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "syifakhrn",
    "password": "12345678",
    "confirmPassword": "12345678",
    "role": "admin"
}

###
// Get All Users
GET http://localhost:5000/users

###
// Get Single User
GET http://localhost:5000/users/d713bb5c-a148-41ec-a760-e1a9c56d3ef5

###
// Update a user
PATCH http://localhost:5000/users/d713bb5c-a148-41ec-a760-e1a9c56d3ef5
Content-Type: application/json

{
    "username": "kingcinunuk",
    "password": "",
    "confirmPassword": "",
    "role": "user"
}

###
// Delete a user
DELETE http://localhost:5000/users/e198f559-9073-4560-ae0c-78d44389495b

###
// Login User Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "syifakhrn",
    "password" : "12345678"
}

###
// Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "rakamahardika",
    "password" : "12345678"
}

###
// Me
GET http://localhost:5000/me

###
// Logout User
DELETE http://localhost:5000/logout

// =================== CRUD IDENTITY ====================

###
// Get All Identities
GET http://localhost:5000/identities

###
// Get Single Identities
GET http://localhost:5000/identities/3

### 
// Create Identity Data
POST http://localhost:5000/identities
Content-Type: application/json

{
    "name": "Syifa Khairina",
    "image": "https://imagesyifa=v44",
    "place_of_birth": "Bandung",
    "date_of_birth": "2003-01-01",
    "address": "Supratman, Bandung",
    "phone_number": "087878876632",
    "email": "syifa.khairina@gmail.com",
    "description": "A passionate web developer with a love for coding.",
    "userId": 1
}

### 
// Create Identity Data
POST http://localhost:5000/identities
Content-Type: application/json

{
    "name": "Raka Mahardika Maulana",
    "image": "https://example.com/raka.jpg",
    "place_of_birth": "Bandung",
    "date_of_birth": "2003-08-17",
    "address": "Cinunuk, Bandung",
    "phone_number": "08184222222",
    "email": "rakamahardika@example.com",
    "description": "A passionate web developer with a love for coding.",
    "userId": 3
}

### 
// Update Identity Data
PATCH http://localhost:5000/identities/3
Content-Type: application/json

{
    
    "twitter": "@cinunukkingdom"
}

### 
// Delete Identity Data
DELETE http://localhost:5000/identities/3

// =================== CRUD ORGANIZATION ====================

###
// Get All Organizations
GET http://localhost:5000/identities/1/organizations

###
// Create an organization
POST http://localhost:5000/identities/1/organizations
Content-Type: application/json

{
    "name_org": "HIMAKOM", 
    "image": "http://www.example.com/brigez.jpg", 
    "start_year": 2021,
    "end_year": 2023,
    "role": "Wakadep PSDA",
    "jobdesc": "Bantuin Kadep"
}

###
// Get Single Organization
GET http://localhost:5000/identities/1/organizations/1

### 
// Update Organization Data
PATCH http://localhost:5000/identities/1/organizations/1
Content-Type: application/json

{
    "start_year": 2019,
    "end_year": 2021,
    "role": "Wakadep MSDH",
    "jobdesc": "Bantuin Kadep Baru"
}

### 
// Delete Organization Data
DELETE http://localhost:5000/identities/1/organizations/1

// =================== CRUD Portfolio ====================
###
// Get All Portfolio
GET http://localhost:5000/identities/1/portfolios

###
// Get Single Portfolio
GET http://localhost:5000/identities/1/portfolios/1

### 
// Delete Portfolio Data
DELETE http://localhost:5000/identities/1/portfolios/2


// =================== CRUD Portfolio Image ====================
###
// Get All Portfolio Image
GET http://localhost:5000/portfolios/1/portfolio_images

###
// Get Single Portfolio Image
GET http://localhost:5000/portfolios/1/portfolio_images/1

### 
// Delete Portfolio Image Data
DELETE http://localhost:5000/portfolios/1/portfolio_images/7

// =================== CRUD Education ====================
###
// Get All Education
GET http://localhost:5000/identities/1/educations

###
// Get Single Education
GET http://localhost:5000/identities/1/educations/1

### 
// Delete Education Data
DELETE http://localhost:5000/identities/1/educations/2

// =================== CRUD Skill ====================
###
// Get All Skill
GET http://localhost:5000/identities/1/skills

###
// Get Single Skill
GET http://localhost:5000/identities/1/skills/1

### 
// Delete Education Skill
DELETE http://localhost:5000/identities/1/skills/2